apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# We reference the operator release manifest that contains CRDs + operator installs.
# resources:
#   - https://raw.githubusercontent.com/arkmq-org/activemq-artemis-operator/main/deploy/crds/broker_activemqartemis_crd.yaml
#   - https://raw.githubusercontent.com/arkmq-org/activemq-artemis-operator/main/deploy/crds/broker_activemqartemisaddress_crd.yaml
#   - https://raw.githubusercontent.com/arkmq-org/activemq-artemis-operator/main/deploy/crds/broker_activemqartemisscaledown_crd.yaml
#   - https://raw.githubusercontent.com/arkmq-org/activemq-artemis-operator/main/deploy/crds/broker_activemqartemissecurity_crd.yaml
#   - https://raw.githubusercontent.com/arkmq-org/activemq-artemis-operator/main/deploy/service_account.yaml
#   - https://raw.githubusercontent.com/arkmq-org/activemq-artemis-operator/main/deploy/cluster_role.yaml
#   - https://raw.githubusercontent.com/arkmq-org/activemq-artemis-operator/main/deploy/cluster_role_binding.yaml
#   - https://raw.githubusercontent.com/arkmq-org/activemq-artemis-operator/main/deploy/election_role.yaml
#   - https://raw.githubusercontent.com/arkmq-org/activemq-artemis-operator/main/deploy/election_role_binding.yaml
#   - https://raw.githubusercontent.com/arkmq-org/activemq-artemis-operator/main/deploy/operator.yaml

resources:
  - https://github.com/arkmq-org/activemq-artemis-operator/releases/download/v2.0.5/activemq-artemis-operator.yaml

commonLabels:
  app: activemq-operator