apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# We reference the operator release manifest that contains CRDs + operator installs.
resources:
  - https://github.com/arkmq-org/activemq-artemis-operator/blob/main/deploy/crds/broker_activemqartemis_crd.yaml
  - https://github.com/arkmq-org/activemq-artemis-operator/blob/main/deploy/crds/broker_activemqartemisaddress_crd.yaml
  - https://github.com/arkmq-org/activemq-artemis-operator/blob/main/deploy/crds/broker_activemqartemisscaledown_crd.yaml
  - https://github.com/arkmq-org/activemq-artemis-operator/blob/main/deploy/crds/broker_activemqartemissecurity_crd.yaml
  - https://github.com/arkmq-org/activemq-artemis-operator/blob/main/deploy/service_account.yaml
  - https://github.com/arkmq-org/activemq-artemis-operator/blob/main/deploy/cluster_role.yaml
  - https://github.com/arkmq-org/activemq-artemis-operator/blob/main/deploy/cluster_role_binding.yaml
  - https://github.com/arkmq-org/activemq-artemis-operator/blob/main/deploy/election_role.yaml
  - https://github.com/arkmq-org/activemq-artemis-operator/blob/main/deploy/election_role_binding.yaml
  - https://github.com/arkmq-org/activemq-artemis-operator/blob/main/deploy/operator.yaml

namespace: activemq-system
commonLabels:
  app: activemq-operator