apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# We reference the operator release manifest that contains CRDs + operator installs.
resources:
  - https://github.com/arkmq-org/activemq-artemis-operator/releases/download/v2.1.0/activemq-artemis-operator.yaml
namespace: activemq-system
commonLabels:
  app: activemq-operator