apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/activemq-ha   # pulls operator + CRDs from upstream release
  - broker-cr.yaml           # your broker custom resource; must be applied after CRDs
namespace: activemq-system




# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
#   - https://raw.githubusercontent.com/artemiscloud/activemq-artemis-operator/v1.2.7/deploy/crds/broker_activemqartemis_crd.yaml
#   - https://raw.githubusercontent.com/artemiscloud/activemq-artemis-operator/v1.2.7/deploy/operator.yaml
#   - broker-cr.yaml   # your CR which relies on the CRD above